//! Renders a [`Detected`] as a starting `rocket.yaml` (Go: `render.go`).

use crate::Detected;
use std::fmt::Write as _;

const YAML_KEYWORDS: [&str; 9] = ["true", "false", "yes", "no", "on", "off", "null", "y", "n"];

/// `^[A-Za-z_][A-Za-z0-9_./-]*$`
fn is_bare_scalar(s: &str) -> bool {
    let mut chars = s.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '/' | '-'))
}

/// Go's `strconv.Quote`: a double-quoted string with Go escapes; printable
/// non-ASCII text stays as is.
pub(crate) fn go_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{7}' => out.push_str("\\a"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{b}' => out.push_str("\\v"),
            c if c == ' ' || (!c.is_control() && !c.is_whitespace()) => out.push(c),
            c if (c as u32) < 0x80 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c if (c as u32) < 0x10000 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => {
                let _ = write!(out, "\\U{:08x}", c as u32);
            }
        }
    }
    out.push('"');
    out
}

/// Renders `s` as a YAML scalar, quoting when needed.
fn q(s: &str) -> String {
    if is_bare_scalar(s) && !YAML_KEYWORDS.contains(&s.to_lowercase().as_str()) {
        s.to_owned()
    } else {
        go_quote(s)
    }
}

fn list(items: &[String]) -> String {
    let parts: Vec<String> = items.iter().map(|s| q(s)).collect();
    format!("[{}]", parts.join(", "))
}

impl Detected {
    /// Returns a rocket.yaml that passes validation. Guesses are marked with
    /// comments for the human to review.
    pub fn render(&self) -> String {
        let mut b = String::new();
        // Writing to a String cannot fail.
        macro_rules! w {
            ($($arg:tt)*) => { let _ = write!(b, $($arg)*); };
        }

        w!("# rocket.yaml generated by `rocket init`; review the guesses before use.\n");
        w!("# Schema: `rocket schema`. Docs: see the rocket README.\n");
        for n in &self.notes {
            w!("# note: {n}\n");
        }
        w!("version: 1\nname: {}\n", q(&self.name));
        if !self.dotenv.is_empty() {
            w!("dotenv: {}\n", list(&self.dotenv));
        }
        if !self.envs.is_empty() {
            w!("default_env: dev\nenvs:\n");
            for (i, e) in self.envs.iter().enumerate() {
                if i > 0 {
                    w!(
                        "  # guessed from {}; rename it (e.g. prod-local) if that is your production stack\n",
                        e.files[0]
                    );
                }
                w!("  {}: {{ compose: {} }}\n", q(&e.name), list(&e.files));
            }
            w!("  # stage: {{ deploy: {{ task: \"release:stage\", confirm: true }} }}\n");
        }
        if !self.setup.is_empty() {
            w!("setup:\n");
            for s in &self.setup {
                w!("  {}: {{ task: {} }}\n", q(&s.name), q(&s.task));
            }
        }

        w!("services:\n");
        let mut compose: Vec<String> = Vec::new();
        let mut tasks: Vec<String> = Vec::new();
        for s in &self.services {
            w!("  {}:\n", q(&s.name));
            if s.compose.is_empty() {
                tasks.push(s.name.clone());
                w!("    task: {}\n", q(&s.task));
                w!(
                    "    # long-running guess; declare its ports so rocket can probe and remap, e.g.\n"
                );
                w!("    # ports: {{ http: {{ default: 3000, env: PORT }} }}\n");
            } else {
                compose.push(s.name.clone());
                w!("    compose: {}\n", q(&s.compose));
            }
            if !s.profiles.is_empty() {
                w!("    profiles: {}\n", list(&s.profiles));
            }
            if !s.ports.is_empty() {
                w!("    ports:\n");
                for p in &s.ports {
                    if p.env.is_empty() {
                        w!(
                            "      # published as a literal port: rocket cannot remap it when busy (use ${{VAR:-{}}} in compose)\n",
                            p.default
                        );
                        w!("      {}: {{ default: {} }}\n", q(&p.name), p.default);
                    } else {
                        w!(
                            "      {}: {{ default: {}, env: {} }}\n",
                            q(&p.name),
                            p.default,
                            q(&p.env)
                        );
                    }
                }
            }
        }
        if self.services.is_empty() {
            w!("  # nothing long-running detected; replace this placeholder\n");
            w!(
                "  app: {{ run: \"echo 'edit rocket.yaml: replace this service' && exec sleep 3600\" }}\n"
            );
        }

        w!("groups:\n");
        let taken = |name: &str| self.services.iter().any(|s| s.name == name);
        if !compose.is_empty() && !taken("containers") {
            w!("  containers: {}\n", list(&compose));
        }
        if !tasks.is_empty() && !taken("dev-tasks") {
            w!("  dev-tasks: {}\n", list(&tasks));
        }
        if !taken("all") {
            w!("  all: [\"*\"]\n");
        }

        if !self.pipelines.is_empty() {
            w!("pipelines:\n");
            for p in &self.pipelines {
                w!("  {}: [{{ task: {} }}]\n", q(p), q(p));
            }
        }
        if !self.deploy_tasks.is_empty() {
            w!(
                "# Deploy-looking tasks (not added as pipelines; wire them as envs.<name>.deploy with confirm: true):\n"
            );
            for t in &self.deploy_tasks {
                w!("#   - {t}\n");
            }
        }
        if !self.tasks.is_empty() {
            w!("# Taskfile tasks detected (any of them runs with `rocket run <task>`):\n");
            for t in &self.tasks {
                if t.desc.is_empty() {
                    w!("#   - {}\n", t.name);
                } else {
                    w!("#   - {} \u{2014} {}\n", t.name, t.desc);
                }
            }
        }
        b
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_only_when_needed() {
        for (input, want) in [
            ("api", "api"),
            ("db:migrate", "\"db:migrate\""),
            ("cp-dev", "cp-dev"),
            ("true", "\"true\""),
            ("No", "\"No\""),
            ("y", "\"y\""),
            ("1abc", "\"1abc\""),
            ("a b", "\"a b\""),
            ("tests/unit.sh", "tests/unit.sh"),
            ("", "\"\""),
        ] {
            assert_eq!(q(input), want, "{input:?}");
        }
    }

    #[test]
    fn go_quote_escapes_like_strconv() {
        assert_eq!(
            go_quote("a\"b\\c\n\t\u{1}\u{7f}"),
            "\"a\\\"b\\\\c\\n\\t\\x01\\x7f\""
        );
        assert_eq!(
            go_quote("caf\u{e9} \u{2014} ok"),
            "\"caf\u{e9} \u{2014} ok\""
        );
        assert_eq!(go_quote("\u{a0}"), "\"\\u00a0\"");
        assert_eq!(go_quote("\u{1f600}"), "\"\u{1f600}\"");
    }
}
