//! TypeScript bindings generated from the Rust DTOs with `ts-rs`.
//!
//! Regenerate `apps/desktop/src/lib/bindings.ts` with
//! `pnpm --dir apps/desktop bindings` (that is
//! `ROCKET_UPDATE_BINDINGS=1 cargo test -p rocket-desktop bindings`). Without
//! the variable the test only fails when the checked-in file is stale.

use crate::dto::{ConnectionStatus, DaemonDetails, FollowMessage};
use crate::error::CommandError;
use crate::update::{InstallEvent, StaleDaemon, UpdateStatus, UpdaterEnv};
use rocket_domain::api::{
    AddProjectRequest, Conflict, DownRequest, DownResult, GcAction, GcResult, HealthInfo,
    JobLogsResult, JobOutcome, JobRequest, JobsResult, LogsResult, PortInfo, PortsResult,
    ProjectInfo, ProjectsResult, RemovedProject, ServiceResult, ShutdownResult, StatusResult,
    Summary, UpRequest, UpResult,
};
use rocket_domain::{
    Event, Health, Job, JobKind, JobStatus, Lease, PortHolder, PortRemap, ProjectRef, Run,
    RunState, ServiceKind, Step,
};
use ts_rs::{Config, TS};

const HEADER: &str = "// Generated by `pnpm bindings` (ts-rs) from the Rust DTOs. Do not edit.\n\n";

macro_rules! decls {
    ($cfg:expr, $($ty:ty),+ $(,)?) => {
        [$(format!("export {}\n", <$ty as TS>::decl($cfg))),+]
    };
}

/// The full contents of `bindings.ts`.
pub fn render() -> String {
    let cfg = Config::new().with_large_int("number");
    let decls = decls!(
        &cfg,
        // domain
        ServiceKind,
        RunState,
        Health,
        JobKind,
        JobStatus,
        Step,
        ProjectRef,
        Run,
        Lease,
        PortHolder,
        PortRemap,
        Event,
        Job,
        // daemon API
        HealthInfo,
        AddProjectRequest,
        ProjectsResult,
        RemovedProject,
        ShutdownResult,
        UpRequest,
        ServiceResult,
        UpResult,
        DownRequest,
        DownResult,
        StatusResult,
        LogsResult,
        PortInfo,
        PortsResult,
        GcAction,
        GcResult,
        ProjectInfo,
        Conflict,
        Summary,
        JobRequest,
        JobsResult,
        JobLogsResult,
        JobOutcome,
        // desktop bridge
        CommandError,
        ConnectionStatus,
        FollowMessage,
        DaemonDetails,
        UpdateStatus,
        InstallEvent,
        UpdaterEnv,
        StaleDaemon,
    );
    format!("{HEADER}{}", decls.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn target() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/bindings.ts")
    }

    #[test]
    fn bindings_are_up_to_date() {
        let want = render();
        if std::env::var_os("ROCKET_UPDATE_BINDINGS").is_some() {
            std::fs::write(target(), &want).expect("write bindings.ts");
            return;
        }
        let have = std::fs::read_to_string(target()).unwrap_or_default();
        assert!(
            have == want,
            "apps/desktop/src/lib/bindings.ts is stale; run `pnpm --dir apps/desktop bindings`"
        );
    }

    #[test]
    fn optional_and_nullable_fields_follow_serde() {
        let ts = render();
        // skip_serializing_if + default => optional key.
        assert!(ts.contains("profiles?: Array<string>"), "{ts}");
        // timestamps travel as RFC3339 strings.
        assert!(ts.contains("started_at"), "{ts}");
        // the wire enum values are string unions.
        assert!(ts.contains("\"starting\""), "{ts}");
    }
}
