// Generated by `pnpm bindings` (ts-rs) from the Rust DTOs. Do not edit.

export type ServiceKind = "compose" | "task" | "run";

export type RunState = "starting" | "running" | "stopping" | "stopped" | "exited" | "failed" | "dead";

export type Health = "unknown" | "healthy" | "unhealthy";

export type JobKind = "setup" | "pipeline" | "deploy";

export type JobStatus = "running" | "succeeded" | "failed" | "canceled" | "lost";

export type Step = { task?: string, run?: string, };

export type ProjectRef = { name: string, path: string, added_at: string, };

export type Run = { project: string, service: string, env: string, kind: ServiceKind, state: RunState, health: Health, pid?: number, pgid?: number, compose_project?: string, 
/**
 * Effective Compose launch profiles; retained for stop.
 */
profiles?: Array<string>, container_id?: string, owner?: string, expires_at?: string, started_at?: string, stopped_at?: string, exit_code?: number | null, ports?: { [key in string]: number }, log_path?: string, error?: string, };

export type Lease = { port: number, project: string, service: string, port_name: string, created_at: string, };

export type PortHolder = { pid: number, command: string, cwd?: string, };

export type PortRemap = { name: string, from: number, to: number, env: string, holder?: PortHolder | null, reason: string, };

export type Event = { type: string, time: string, project?: string, service?: string, state?: RunState | null, line?: string, run?: Run | null, lease?: Lease | null, job_id?: string, 
/**
 * `job.state` only.
 */
status?: JobStatus | null, 
/**
 * `job.state` only.
 */
job?: Job | null, };

export type Job = { id: string, project: string, 
/**
 * Pipeline/task name, setup name or deploy env.
 */
name: string, kind: JobKind, 
/**
 * Selected environment; deploy target for deploy jobs.
 */
env?: string, 
/**
 * Effective env/request startup selection for prerequisites.
 */
profiles?: Array<string>, owner: string, steps: Array<Step>, 
/**
 * Appended to the last step.
 */
args?: Array<string>, status: JobStatus, 
/**
 * 1-based index of the current/last step.
 */
step?: number, pid?: number, pgid?: number, exit_code?: number | null, started_at: string, expires_at?: string, finished_at?: string, duration_ms: number, log_path?: string, error?: string, };

export type HealthInfo = { ok: boolean, api: string, version: string, pid: number, started_at: string, home: string, socket: string, 
/**
 * The token-protected TCP listener; omitted when it could not bind.
 */
http?: string, };

export type AddProjectRequest = { path: string, };

export type ProjectsResult = { projects: Array<ProjectRef>, };

export type RemovedProject = { removed: string, };

export type ShutdownResult = { ok: boolean, pid: number, };

export type UpRequest = { 
/**
 * Absolute path or registered name.
 */
project: string, 
/**
 * Services or groups; empty means everything.
 */
services?: Array<string>, 
/**
 * Defaults to the project's default env.
 */
env?: string, 
/**
 * Extra profiles enabled for wildcard selection.
 */
profiles?: Array<string>, 
/**
 * Defaults to `user`.
 */
owner?: string, 
/**
 * Go duration, e.g. `30m`.
 */
ttl?: string, };

export type ServiceResult = { service: string, 
/**
 * See [`service_action`].
 */
action: string, state: RunState, health?: Health | null, pid?: number, ports?: { [key in string]: number }, remaps?: Array<PortRemap>, owner?: string, expires_at?: string, log_path?: string, error?: string, };

export type UpResult = { project: string, env: string, services: Array<ServiceResult>, hints?: Array<string>, };

export type DownRequest = { 
/**
 * Path or name; ignored with `everywhere`.
 */
project?: string, 
/**
 * Services or groups; empty means the whole project.
 */
services?: Array<string>, 
/**
 * Only runs started by this owner.
 */
owner?: string, 
/**
 * All projects.
 */
everywhere?: boolean, };

export type DownResult = { stopped: Array<Run>, 
/**
 * Compose projects taken down.
 */
compose_down?: Array<string>, 
/**
 * Running jobs canceled by a whole-project/owner/everywhere `down`.
 */
canceled_jobs?: Array<string>, errors?: Array<string>, };

export type StatusResult = { services: Array<Run>, };

export type LogsResult = { project: string, service: string, lines: Array<string>, };

export type PortInfo = { owner?: string, state?: RunState | null, pid?: number, env?: string, port: number, project: string, service: string, port_name: string, created_at: string, };

export type PortsResult = { ports: Array<PortInfo>, };

export type GcAction = { action: string, project: string, service: string, port?: number, detail?: string, };

export type GcResult = { actions: Array<GcAction>, };

export type ProjectInfo = { name: string, root: string, default_env: string, envs?: Array<string> | null, pipelines?: Array<string> | null, deploy_envs?: Array<string> | null, };

export type Conflict = { kind: string, project: string, service: string, port_name: string, 
/**
 * Remapped port, or the busy default.
 */
port: number, 
/**
 * Port declared in rocket.yaml.
 */
default: number, env?: string, 
/**
 * Whether the service declares an env var rocket can inject.
 */
remappable: boolean, holder?: PortHolder | null, detail: string, };

export type Summary = { project?: ProjectInfo | null, services: Array<Run>, 
/**
 * Running jobs only.
 */
jobs: Array<Job>, conflicts: Array<Conflict>, };

export type JobRequest = { project: string, kind: JobKind, 
/**
 * Pipeline/task, setup name or deploy env.
 */
name?: string, env?: string, profiles?: Array<string>, 
/**
 * Positive Go duration measured from job creation.
 */
ttl?: string, 
/**
 * Appended to the last step.
 */
args?: Array<string>, owner?: string, 
/**
 * Confirms a deploy to an env with `confirm: true`.
 */
yes?: boolean, 
/**
 * Lets an `agent:` owner deploy (CLI sets it from `ROCKET_ALLOW_DEPLOY`).
 */
allow_agent_deploy?: boolean, };

export type JobsResult = { jobs: Array<Job>, };

export type JobLogsResult = { job: string, project: string, lines: Array<string>, };

export type JobOutcome = { job: string, project: string, kind: JobKind, name: string, status: JobStatus, exit_code: number | null, duration_ms: number, log_path: string, tail: Array<string>, error?: string, };

export type CommandError = { code: string, message: string, 
/**
 * HTTP status of a daemon answer; `null` for local failures.
 */
status: number | null, };

export type ConnectionStatus = { "state": "connecting" } | { "state": "online", version: string, pid: number, } | { "state": "offline", reason: string, };

export type FollowMessage = { "kind": "event", event: Event, } | { "kind": "end" } | { "kind": "error", message: string, };

export type DaemonDetails = { running: boolean, home: string, socket: string, db: string, logs: string, daemon_log: string, daemon_json: string, 
/**
 * The rocket binary the app would launch, when one is found.
 */
rocket_bin: string | null, health: HealthInfo | null, 
/**
 * Non-fatal problems, e.g. `daemon.json` readable by other users.
 */
warnings: Array<string>, };

export type UpdateStatus = { available: boolean, 
/**
 * The announced version; `null` when up to date.
 */
version: string | null, current_version: string, notes: string | null, 
/**
 * RFC3339 publish date, when the manifest carries one.
 */
date: string | null, };

export type InstallEvent = { "event": "started", content_length: number | null, } | { "event": "progress", chunk: number, } | { "event": "finished" };

export type UpdaterEnv = { current_version: string, 
/**
 * `false` in debug builds: no automatic checks while developing.
 */
auto_check: boolean, };

export type StaleDaemon = { running: string, bundled: string, };
