# This file was generated by GoReleaser. DO NOT EDIT.
cask "rocket" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "0380e5953f5201de5b3e0e5d0dd89182690ae94cf3cbc454f0a8c5ea300c18b8"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf7132b622328f0ea77629d89d88b85fe26ea5ffe50fa1bac3d146f5202b21fb"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5a3dd0d54a06068263ac4cd3e526efd341487076e977b485a75e0d105328d17c"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b23f2653ed5f4c353866e26ea74f9675f4392402befc1feab772898a9cbbb128"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rocket"
  desc "Supervise dev processes for humans and AI agents"
  homepage "https://github.com/xean-io/rocket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rocket"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rocket"]
    end
  end

  # No zap stanza required
end
