# This file was generated by GoReleaser. DO NOT EDIT.
cask "rocket" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "3985afd8437d6e2db2352dda00da7c0313a0802588ad98c700d7a3acf656ea64"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "56b42027e388a5590a4e3dd8656228bf5a536c395010126d77fffdb11466439b"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "83f51ebd1c95302d212c29c8ff1d109984cd58efb304bd2bdb6a7564bcf5927d"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73864f71d59008b7f77e29a4247f8ae26fa8b621d59fb8e9e4e3a1bd0764246d"
      url "https://github.com/xean-io/rocket/releases/download/v#{version}/rocket_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rocket"
  desc "Supervise dev processes for humans and AI agents"
  homepage "https://github.com/xean-io/rocket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rocket"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rocket"]
    end
  end

  # No zap stanza required
end
