# Cask for the Rocket desktop app (universal macOS dmg).
#
# TEMPLATE: the release workflow (.github/workflows/release.yml, job
# `desktop`) overwrites `version` and `sha256` below after uploading
# Rocket_<version>_universal.dmg to the GitHub release, then commits this file
# to main. The sha256 here is a placeholder and does not match any real dmg.
# The CLI cask (rocket.rb) is generated by GoReleaser and already provides the
# `rocket` binary, so this cask installs only the app: no `binary` stanza.
cask "rocket-app" do
  version "0.1.1"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/xean-io/rocket/releases/download/v#{version}/Rocket_#{version}_universal.dmg"
  name "Rocket"
  desc "Desktop app to supervise dev processes for humans and AI agents"
  homepage "https://github.com/xean-io/rocket"

  livecheck do
    skip "Auto-generated on release."
  end

  # The app updates itself (Tauri updater): `brew upgrade` leaves it alone
  # unless run with --greedy.
  auto_updates true

  depends_on macos: ">= :big_sur"

  app "Rocket.app"

  postflight do
    # The app is ad-hoc signed, not notarized; drop the quarantine bit so macOS opens it.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Rocket.app"]
  end

  # No zap stanza: ~/.rocket is shared with the CLI and holds user state.
end
