package scaffold

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

var (
	bareScalarRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_./-]*$`)
	yamlKeywords = map[string]bool{"true": true, "false": true, "yes": true, "no": true, "on": true, "off": true, "null": true, "y": true, "n": true}
)

// q renders s as a YAML scalar, quoting when needed.
func q(s string) string {
	if bareScalarRe.MatchString(s) && !yamlKeywords[strings.ToLower(s)] {
		return s
	}
	return strconv.Quote(s)
}

func list(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = q(s)
	}
	return "[" + strings.Join(out, ", ") + "]"
}

// Render returns a rocket.yaml that passes validation. Guesses are marked
// with comments for the human to review.
func (r *Result) Render() []byte {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# rocket.yaml generated by `rocket init`; review the guesses before use.\n")
	w("# Schema: `rocket schema`. Docs: see the rocket README.\n")
	for _, n := range r.Notes {
		w("# note: %s\n", n)
	}
	w("version: 1\nname: %s\n", q(r.Name))
	if len(r.Dotenv) > 0 {
		w("dotenv: %s\n", list(r.Dotenv))
	}
	if len(r.Envs) > 0 {
		w("default_env: dev\nenvs:\n")
		for i, e := range r.Envs {
			if i > 0 {
				w("  # guessed from %s; rename it (e.g. prod-local) if that is your production stack\n", e.Files[0])
			}
			w("  %s: { compose: %s }\n", q(e.Name), list(e.Files))
		}
		w("  # stage: { deploy: { task: \"release:stage\", confirm: true } }\n")
	}
	if len(r.Setup) > 0 {
		w("setup:\n")
		for _, s := range r.Setup {
			w("  %s: { task: %s }\n", q(s.Name), q(s.Task))
		}
	}

	w("services:\n")
	var compose, tasks []string
	for _, s := range r.Services {
		w("  %s:\n", q(s.Name))
		if s.Compose != "" {
			compose = append(compose, s.Name)
			w("    compose: %s\n", q(s.Compose))
		} else {
			tasks = append(tasks, s.Name)
			w("    task: %s\n", q(s.Task))
			w("    # long-running guess; declare its ports so rocket can probe and remap, e.g.\n")
			w("    # ports: { http: { default: 3000, env: PORT } }\n")
		}
		if len(s.Profiles) > 0 {
			w("    profiles: %s\n", list(s.Profiles))
		}
		if len(s.Ports) > 0 {
			w("    ports:\n")
			for _, p := range s.Ports {
				if p.Env == "" {
					w("      # published as a literal port: rocket cannot remap it when busy (use ${VAR:-%d} in compose)\n", p.Default)
					w("      %s: { default: %d }\n", q(p.Name), p.Default)
				} else {
					w("      %s: { default: %d, env: %s }\n", q(p.Name), p.Default, q(p.Env))
				}
			}
		}
	}
	if len(r.Services) == 0 {
		w("  # nothing long-running detected; replace this placeholder\n")
		w("  app: { run: \"echo 'edit rocket.yaml: replace this service' && exec sleep 3600\" }\n")
	}

	w("groups:\n")
	taken := map[string]bool{}
	for _, s := range r.Services {
		taken[s.Name] = true
	}
	if len(compose) > 0 && !taken["containers"] {
		w("  containers: %s\n", list(compose))
	}
	if len(tasks) > 0 && !taken["dev-tasks"] {
		w("  dev-tasks: %s\n", list(tasks))
	}
	if !taken["all"] {
		w("  all: [\"*\"]\n")
	}

	if len(r.Pipelines) > 0 {
		w("pipelines:\n")
		for _, p := range r.Pipelines {
			w("  %s: [{ task: %s }]\n", q(p), q(p))
		}
	}
	if len(r.DeployTasks) > 0 {
		w("# Deploy-looking tasks (not added as pipelines; wire them as envs.<name>.deploy with confirm: true):\n")
		for _, t := range r.DeployTasks {
			w("#   - %s\n", t)
		}
	}
	if len(r.Tasks) > 0 {
		w("# Taskfile tasks detected (any of them runs with `rocket run <task>`):\n")
		for _, t := range r.Tasks {
			if t.Desc != "" {
				w("#   - %s — %s\n", t.Name, t.Desc)
			} else {
				w("#   - %s\n", t.Name)
			}
		}
	}
	return b.Bytes()
}
